# W&B Configuration
api_key: "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"
project: "breast-cancer-final"
entity: "tgijayesh-dayananda-sagar-university"
job_type: "training"
tags:
  - "breast-cancer"
  - "final"
  - "quantum-local"
log_model: true
log_gradients: false
log_weights: false
save_code: true
log_images: false
log_gradcam: false
log_interval: 10
val_log_interval: 1
use_sweep: false
